# 服务端口
server:
  port: 8110

#spring设置
spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-core # 服务名
  datasource: # mysql数据库连接
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/srb_core?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password:
    #Swagger2,
    #springboot2.6.x之后将spring MVC默认路径匹配策略从ANT_PATH_MATCHER模式改为PATH_PATTERN_PARSER模式导致出错，解决方法是切换会原先的ANT_PATH_MATCHER模式
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#mybatis
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/com/yyl/srb/core/mapper/xml/*.xml


#  logging:
#    config:
#      classpath: logback-spring.xml